// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/flows/v1/flows.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-06-24 12:08:13 UTC

package v1

const (
	// FlowsService_GetFlow_FullMethodDescription returns the description of the alis.open.flows.v1.FlowsService.GetFlow method.
	FlowsService_GetFlow_FullMethodDescription = ""
	// FlowsService_ListFlows_FullMethodDescription returns the description of the alis.open.flows.v1.FlowsService.ListFlows method.
	FlowsService_ListFlows_FullMethodDescription = ""
	// FlowsService_StreamFlows_FullMethodDescription returns the description of the alis.open.flows.v1.FlowsService.StreamFlows method.
	FlowsService_StreamFlows_FullMethodDescription = ""
	// FlowsService_GenerateFlowTree_FullMethodDescription returns the description of the alis.open.flows.v1.FlowsService.GenerateFlowTree method.
	FlowsService_GenerateFlowTree_FullMethodDescription = ""
	// FlowsService_HandleEvent_FullMethodDescription returns the description of the alis.open.flows.v1.FlowsService.HandleEvent method.
	FlowsService_HandleEvent_FullMethodDescription = ""
	// FlowsService_HandleDeadLetter_FullMethodDescription returns the description of the alis.open.flows.v1.FlowsService.HandleDeadLetter method.
	FlowsService_HandleDeadLetter_FullMethodDescription = ""
)
