// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/operations/v1/operations.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-02 09:33:10 UTC

package operations

const ()
