// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: alis/open/operations/v1/operations.proto

package operations

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata *anypb.Any             `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Done     bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Operation_Error
	//	*Operation_Response
	Result        isOperation_Result `protobuf_oneof:"result"`
	Method        string             `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Checkpoint    string             `protobuf:"bytes,9,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	InternalState []byte             `protobuf:"bytes,10,opt,name=internal_state,json=internalState,proto3" json:"internal_state,omitempty"`
	// Types that are valid to be assigned to Runner:
	//
	//	*Operation_CloudTask_
	Runner        isOperation_Runner     `protobuf_oneof:"runner"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_alis_open_operations_v1_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_operations_v1_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_alis_open_operations_v1_operations_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operation) GetMetadata() *anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Operation) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Operation) GetResult() isOperation_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Operation) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Result.(*Operation_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Operation) GetResponse() *anypb.Any {
	if x != nil {
		if x, ok := x.Result.(*Operation_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Operation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Operation) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

func (x *Operation) GetInternalState() []byte {
	if x != nil {
		return x.InternalState
	}
	return nil
}

func (x *Operation) GetRunner() isOperation_Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

func (x *Operation) GetCloudTask() *Operation_CloudTask {
	if x != nil {
		if x, ok := x.Runner.(*Operation_CloudTask_); ok {
			return x.CloudTask
		}
	}
	return nil
}

func (x *Operation) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Operation) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type isOperation_Result interface {
	isOperation_Result()
}

type Operation_Error struct {
	Error *status.Status `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type Operation_Response struct {
	Response *anypb.Any `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

func (*Operation_Error) isOperation_Result() {}

func (*Operation_Response) isOperation_Result() {}

type isOperation_Runner interface {
	isOperation_Runner()
}

type Operation_CloudTask_ struct {
	CloudTask *Operation_CloudTask `protobuf:"bytes,11,opt,name=cloud_task,json=cloudTask,proto3,oneof"`
}

func (*Operation_CloudTask_) isOperation_Runner() {}

type Operation_CloudTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ScheduleTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=schedule_time,json=scheduleTime,proto3" json:"schedule_time,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Running       bool                   `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	TargetHost    string                 `protobuf:"bytes,5,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation_CloudTask) Reset() {
	*x = Operation_CloudTask{}
	mi := &file_alis_open_operations_v1_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation_CloudTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation_CloudTask) ProtoMessage() {}

func (x *Operation_CloudTask) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_operations_v1_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation_CloudTask.ProtoReflect.Descriptor instead.
func (*Operation_CloudTask) Descriptor() ([]byte, []int) {
	return file_alis_open_operations_v1_operations_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Operation_CloudTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operation_CloudTask) GetScheduleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleTime
	}
	return nil
}

func (x *Operation_CloudTask) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Operation_CloudTask) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *Operation_CloudTask) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

var File_alis_open_operations_v1_operations_proto protoreflect.FileDescriptor

const file_alis_open_operations_v1_operations_proto_rawDesc = "" +
	"\n" +
	"(alis/open/operations/v1/operations.proto\x12\x17alis.open.operations.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\"\xe8\x05\n" +
	"\tOperation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\bmetadata\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.google.rpc.StatusH\x00R\x05error\x122\n" +
	"\bresponse\x18\x05 \x01(\v2\x14.google.protobuf.AnyH\x00R\bresponse\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\t \x01(\tR\n" +
	"checkpoint\x12%\n" +
	"\x0einternal_state\x18\n" +
	" \x01(\fR\rinternalState\x12M\n" +
	"\n" +
	"cloud_task\x18\v \x01(\v2,.alis.open.operations.v1.Operation.CloudTaskH\x01R\tcloudTask\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x1a\xd8\x01\n" +
	"\tCloudTask\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\rschedule_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduleTime\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x18\n" +
	"\arunning\x18\x04 \x01(\bR\arunning\x12\x1f\n" +
	"\vtarget_host\x18\x05 \x01(\tR\n" +
	"targetHostB\b\n" +
	"\x06resultB\b\n" +
	"\x06runnerJ\x04\b\a\x10\bJ\x04\b\b\x10\tB6Z4github.com/alis-build/public-go/alis/open/operationsb\x06proto3"

var (
	file_alis_open_operations_v1_operations_proto_rawDescOnce sync.Once
	file_alis_open_operations_v1_operations_proto_rawDescData []byte
)

func file_alis_open_operations_v1_operations_proto_rawDescGZIP() []byte {
	file_alis_open_operations_v1_operations_proto_rawDescOnce.Do(func() {
		file_alis_open_operations_v1_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_open_operations_v1_operations_proto_rawDesc), len(file_alis_open_operations_v1_operations_proto_rawDesc)))
	})
	return file_alis_open_operations_v1_operations_proto_rawDescData
}

var file_alis_open_operations_v1_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alis_open_operations_v1_operations_proto_goTypes = []any{
	(*Operation)(nil),             // 0: alis.open.operations.v1.Operation
	(*Operation_CloudTask)(nil),   // 1: alis.open.operations.v1.Operation.CloudTask
	(*anypb.Any)(nil),             // 2: google.protobuf.Any
	(*status.Status)(nil),         // 3: google.rpc.Status
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_alis_open_operations_v1_operations_proto_depIdxs = []int32{
	2, // 0: alis.open.operations.v1.Operation.metadata:type_name -> google.protobuf.Any
	3, // 1: alis.open.operations.v1.Operation.error:type_name -> google.rpc.Status
	2, // 2: alis.open.operations.v1.Operation.response:type_name -> google.protobuf.Any
	1, // 3: alis.open.operations.v1.Operation.cloud_task:type_name -> alis.open.operations.v1.Operation.CloudTask
	4, // 4: alis.open.operations.v1.Operation.create_time:type_name -> google.protobuf.Timestamp
	4, // 5: alis.open.operations.v1.Operation.update_time:type_name -> google.protobuf.Timestamp
	4, // 6: alis.open.operations.v1.Operation.CloudTask.schedule_time:type_name -> google.protobuf.Timestamp
	4, // 7: alis.open.operations.v1.Operation.CloudTask.create_time:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_alis_open_operations_v1_operations_proto_init() }
func file_alis_open_operations_v1_operations_proto_init() {
	if File_alis_open_operations_v1_operations_proto != nil {
		return
	}
	file_alis_open_operations_v1_operations_proto_msgTypes[0].OneofWrappers = []any{
		(*Operation_Error)(nil),
		(*Operation_Response)(nil),
		(*Operation_CloudTask_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_open_operations_v1_operations_proto_rawDesc), len(file_alis_open_operations_v1_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_open_operations_v1_operations_proto_goTypes,
		DependencyIndexes: file_alis_open_operations_v1_operations_proto_depIdxs,
		MessageInfos:      file_alis_open_operations_v1_operations_proto_msgTypes,
	}.Build()
	File_alis_open_operations_v1_operations_proto = out.File
	file_alis_open_operations_v1_operations_proto_goTypes = nil
	file_alis_open_operations_v1_operations_proto_depIdxs = nil
}
