// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: alis/open/flows/v1/flows.proto

package flows

import (
	v1 "github.com/alis-build/public-go/alis/open/pubsub/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Flow_Step_State int32

const (
	Flow_Step_STATE_UNSPECIFIED Flow_Step_State = 0
	Flow_Step_QUEUED            Flow_Step_State = 1
	Flow_Step_IN_PROGRESS       Flow_Step_State = 2
	Flow_Step_CANCELLED         Flow_Step_State = 3
	Flow_Step_COMPLETED         Flow_Step_State = 4
	Flow_Step_FAILED            Flow_Step_State = 5
	Flow_Step_AWAITING_INPUT    Flow_Step_State = 6
)

// Enum value maps for Flow_Step_State.
var (
	Flow_Step_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "QUEUED",
		2: "IN_PROGRESS",
		3: "CANCELLED",
		4: "COMPLETED",
		5: "FAILED",
		6: "AWAITING_INPUT",
	}
	Flow_Step_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"QUEUED":            1,
		"IN_PROGRESS":       2,
		"CANCELLED":         3,
		"COMPLETED":         4,
		"FAILED":            5,
		"AWAITING_INPUT":    6,
	}
)

func (x Flow_Step_State) Enum() *Flow_Step_State {
	p := new(Flow_Step_State)
	*p = x
	return p
}

func (x Flow_Step_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Flow_Step_State) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_open_flows_v1_flows_proto_enumTypes[0].Descriptor()
}

func (Flow_Step_State) Type() protoreflect.EnumType {
	return &file_alis_open_flows_v1_flows_proto_enumTypes[0]
}

func (x Flow_Step_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Flow_Step_State.Descriptor instead.
func (Flow_Step_State) EnumDescriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Flow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Steps         []*Flow_Step           `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,97,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	PublishTime   *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{0}
}

func (x *Flow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flow) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Flow) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Flow) GetSteps() []*Flow_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Flow) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Flow) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Flow) GetPublishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishTime
	}
	return nil
}

type GetFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowRequest) Reset() {
	*x = GetFlowRequest{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowRequest) ProtoMessage() {}

func (x *GetFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowRequest.ProtoReflect.Descriptor instead.
func (*GetFlowRequest) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFlowRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ListFlowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	Filter        string                 `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowsRequest) Reset() {
	*x = ListFlowsRequest{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowsRequest) ProtoMessage() {}

func (x *ListFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowsRequest.ProtoReflect.Descriptor instead.
func (*ListFlowsRequest) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{2}
}

func (x *ListFlowsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListFlowsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFlowsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListFlowsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *ListFlowsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListFlowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*Flow                `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowsResponse) Reset() {
	*x = ListFlowsResponse{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowsResponse) ProtoMessage() {}

func (x *ListFlowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowsResponse.ProtoReflect.Descriptor instead.
func (*ListFlowsResponse) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{3}
}

func (x *ListFlowsResponse) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *ListFlowsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type StreamFlowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFlowsRequest) Reset() {
	*x = StreamFlowsRequest{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFlowsRequest) ProtoMessage() {}

func (x *StreamFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFlowsRequest.ProtoReflect.Descriptor instead.
func (*StreamFlowsRequest) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{4}
}

func (x *StreamFlowsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *StreamFlowsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type GenerateFlowTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxDepth      int32                  `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFlowTreeRequest) Reset() {
	*x = GenerateFlowTreeRequest{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFlowTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFlowTreeRequest) ProtoMessage() {}

func (x *GenerateFlowTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFlowTreeRequest.ProtoReflect.Descriptor instead.
func (*GenerateFlowTreeRequest) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateFlowTreeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateFlowTreeRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *GenerateFlowTreeRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *GenerateFlowTreeRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type GenerateFlowTreeResponse struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Flow          *Flow                                    `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	StepChildren  []*GenerateFlowTreeResponse_StepChildren `protobuf:"bytes,2,rep,name=step_children,json=stepChildren,proto3" json:"step_children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFlowTreeResponse) Reset() {
	*x = GenerateFlowTreeResponse{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFlowTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFlowTreeResponse) ProtoMessage() {}

func (x *GenerateFlowTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFlowTreeResponse.ProtoReflect.Descriptor instead.
func (*GenerateFlowTreeResponse) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateFlowTreeResponse) GetFlow() *Flow {
	if x != nil {
		return x.Flow
	}
	return nil
}

func (x *GenerateFlowTreeResponse) GetStepChildren() []*GenerateFlowTreeResponse_StepChildren {
	if x != nil {
		return x.StepChildren
	}
	return nil
}

type Flow_Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	State         Flow_Step_State        `protobuf:"varint,4,opt,name=state,proto3,enum=alis.open.flows.v1.Flow_Step_State" json:"state,omitempty"`
	Children      []*Flow                `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow_Step) Reset() {
	*x = Flow_Step{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow_Step) ProtoMessage() {}

func (x *Flow_Step) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow_Step.ProtoReflect.Descriptor instead.
func (*Flow_Step) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Flow_Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flow_Step) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Flow_Step) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flow_Step) GetState() Flow_Step_State {
	if x != nil {
		return x.State
	}
	return Flow_Step_STATE_UNSPECIFIED
}

func (x *Flow_Step) GetChildren() []*Flow {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Flow_Step) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Flow_Step) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type GenerateFlowTreeResponse_StepChildren struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Children      []string               `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFlowTreeResponse_StepChildren) Reset() {
	*x = GenerateFlowTreeResponse_StepChildren{}
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFlowTreeResponse_StepChildren) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFlowTreeResponse_StepChildren) ProtoMessage() {}

func (x *GenerateFlowTreeResponse_StepChildren) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_flows_v1_flows_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFlowTreeResponse_StepChildren.ProtoReflect.Descriptor instead.
func (*GenerateFlowTreeResponse_StepChildren) Descriptor() ([]byte, []int) {
	return file_alis_open_flows_v1_flows_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GenerateFlowTreeResponse_StepChildren) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerateFlowTreeResponse_StepChildren) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_alis_open_flows_v1_flows_proto protoreflect.FileDescriptor

const file_alis_open_flows_v1_flows_proto_rawDesc = "" +
	"\n" +
	"\x1ealis/open/flows/v1/flows.proto\x12\x12alis.open.flows.v1\x1a alis/open/pubsub/v1/pubsub.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x06\n" +
	"\x04Flow\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x123\n" +
	"\x05steps\x18\a \x03(\v2\x1d.alis.open.flows.v1.Flow.StepR\x05steps\x12;\n" +
	"\vcreate_time\x18a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12=\n" +
	"\fpublish_time\x18c \x01(\v2\x1a.google.protobuf.TimestampR\vpublishTime\x1a\xc6\x03\n" +
	"\x04Step\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\x05state\x18\x04 \x01(\x0e2#.alis.open.flows.v1.Flow.Step.StateR\x05state\x124\n" +
	"\bchildren\x18\b \x03(\v2\x18.alis.open.flows.v1.FlowR\bchildren\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"y\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\x12\x12\n" +
	"\x0eAWAITING_INPUT\x10\x06J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"]\n" +
	"\x0eGetFlowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xb7\x01\n" +
	"\x10ListFlowsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\"k\n" +
	"\x11ListFlowsResponse\x12.\n" +
	"\x05flows\x18\x01 \x03(\v2\x18.alis.open.flows.v1.FlowR\x05flows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"e\n" +
	"\x12StreamFlowsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\x9b\x01\n" +
	"\x17GenerateFlowTreeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"\xe4\x01\n" +
	"\x18GenerateFlowTreeResponse\x12,\n" +
	"\x04flow\x18\x01 \x01(\v2\x18.alis.open.flows.v1.FlowR\x04flow\x12^\n" +
	"\rstep_children\x18\x02 \x03(\v29.alis.open.flows.v1.GenerateFlowTreeResponse.StepChildrenR\fstepChildren\x1a:\n" +
	"\fStepChildren\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bchildren\x18\x02 \x03(\tR\bchildren2\x9a\x04\n" +
	"\fFlowsService\x12I\n" +
	"\aGetFlow\x12\".alis.open.flows.v1.GetFlowRequest\x1a\x18.alis.open.flows.v1.Flow\"\x00\x12Z\n" +
	"\tListFlows\x12$.alis.open.flows.v1.ListFlowsRequest\x1a%.alis.open.flows.v1.ListFlowsResponse\"\x00\x12S\n" +
	"\vStreamFlows\x12&.alis.open.flows.v1.StreamFlowsRequest\x1a\x18.alis.open.flows.v1.Flow\"\x000\x01\x12o\n" +
	"\x10GenerateFlowTree\x12+.alis.open.flows.v1.GenerateFlowTreeRequest\x1a,.alis.open.flows.v1.GenerateFlowTreeResponse\"\x00\x12K\n" +
	"\vHandleEvent\x12\".alis.open.pubsub.v1.PubSubMessage\x1a\x16.google.protobuf.Empty\"\x00\x12P\n" +
	"\x10HandleDeadLetter\x12\".alis.open.pubsub.v1.PubSubMessage\x1a\x16.google.protobuf.Empty\"\x00B1Z/github.com/alis-build/public-go/alis/open/flowsb\x06proto3"

var (
	file_alis_open_flows_v1_flows_proto_rawDescOnce sync.Once
	file_alis_open_flows_v1_flows_proto_rawDescData []byte
)

func file_alis_open_flows_v1_flows_proto_rawDescGZIP() []byte {
	file_alis_open_flows_v1_flows_proto_rawDescOnce.Do(func() {
		file_alis_open_flows_v1_flows_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_open_flows_v1_flows_proto_rawDesc), len(file_alis_open_flows_v1_flows_proto_rawDesc)))
	})
	return file_alis_open_flows_v1_flows_proto_rawDescData
}

var file_alis_open_flows_v1_flows_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alis_open_flows_v1_flows_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_alis_open_flows_v1_flows_proto_goTypes = []any{
	(Flow_Step_State)(0),                          // 0: alis.open.flows.v1.Flow.Step.State
	(*Flow)(nil),                                  // 1: alis.open.flows.v1.Flow
	(*GetFlowRequest)(nil),                        // 2: alis.open.flows.v1.GetFlowRequest
	(*ListFlowsRequest)(nil),                      // 3: alis.open.flows.v1.ListFlowsRequest
	(*ListFlowsResponse)(nil),                     // 4: alis.open.flows.v1.ListFlowsResponse
	(*StreamFlowsRequest)(nil),                    // 5: alis.open.flows.v1.StreamFlowsRequest
	(*GenerateFlowTreeRequest)(nil),               // 6: alis.open.flows.v1.GenerateFlowTreeRequest
	(*GenerateFlowTreeResponse)(nil),              // 7: alis.open.flows.v1.GenerateFlowTreeResponse
	(*Flow_Step)(nil),                             // 8: alis.open.flows.v1.Flow.Step
	(*GenerateFlowTreeResponse_StepChildren)(nil), // 9: alis.open.flows.v1.GenerateFlowTreeResponse.StepChildren
	(*timestamppb.Timestamp)(nil),                 // 10: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),                 // 11: google.protobuf.FieldMask
	(*v1.PubSubMessage)(nil),                      // 12: alis.open.pubsub.v1.PubSubMessage
	(*emptypb.Empty)(nil),                         // 13: google.protobuf.Empty
}
var file_alis_open_flows_v1_flows_proto_depIdxs = []int32{
	8,  // 0: alis.open.flows.v1.Flow.steps:type_name -> alis.open.flows.v1.Flow.Step
	10, // 1: alis.open.flows.v1.Flow.create_time:type_name -> google.protobuf.Timestamp
	10, // 2: alis.open.flows.v1.Flow.update_time:type_name -> google.protobuf.Timestamp
	10, // 3: alis.open.flows.v1.Flow.publish_time:type_name -> google.protobuf.Timestamp
	11, // 4: alis.open.flows.v1.GetFlowRequest.read_mask:type_name -> google.protobuf.FieldMask
	11, // 5: alis.open.flows.v1.ListFlowsRequest.read_mask:type_name -> google.protobuf.FieldMask
	1,  // 6: alis.open.flows.v1.ListFlowsResponse.flows:type_name -> alis.open.flows.v1.Flow
	11, // 7: alis.open.flows.v1.StreamFlowsRequest.read_mask:type_name -> google.protobuf.FieldMask
	11, // 8: alis.open.flows.v1.GenerateFlowTreeRequest.read_mask:type_name -> google.protobuf.FieldMask
	1,  // 9: alis.open.flows.v1.GenerateFlowTreeResponse.flow:type_name -> alis.open.flows.v1.Flow
	9,  // 10: alis.open.flows.v1.GenerateFlowTreeResponse.step_children:type_name -> alis.open.flows.v1.GenerateFlowTreeResponse.StepChildren
	0,  // 11: alis.open.flows.v1.Flow.Step.state:type_name -> alis.open.flows.v1.Flow.Step.State
	1,  // 12: alis.open.flows.v1.Flow.Step.children:type_name -> alis.open.flows.v1.Flow
	10, // 13: alis.open.flows.v1.Flow.Step.create_time:type_name -> google.protobuf.Timestamp
	10, // 14: alis.open.flows.v1.Flow.Step.update_time:type_name -> google.protobuf.Timestamp
	2,  // 15: alis.open.flows.v1.FlowsService.GetFlow:input_type -> alis.open.flows.v1.GetFlowRequest
	3,  // 16: alis.open.flows.v1.FlowsService.ListFlows:input_type -> alis.open.flows.v1.ListFlowsRequest
	5,  // 17: alis.open.flows.v1.FlowsService.StreamFlows:input_type -> alis.open.flows.v1.StreamFlowsRequest
	6,  // 18: alis.open.flows.v1.FlowsService.GenerateFlowTree:input_type -> alis.open.flows.v1.GenerateFlowTreeRequest
	12, // 19: alis.open.flows.v1.FlowsService.HandleEvent:input_type -> alis.open.pubsub.v1.PubSubMessage
	12, // 20: alis.open.flows.v1.FlowsService.HandleDeadLetter:input_type -> alis.open.pubsub.v1.PubSubMessage
	1,  // 21: alis.open.flows.v1.FlowsService.GetFlow:output_type -> alis.open.flows.v1.Flow
	4,  // 22: alis.open.flows.v1.FlowsService.ListFlows:output_type -> alis.open.flows.v1.ListFlowsResponse
	1,  // 23: alis.open.flows.v1.FlowsService.StreamFlows:output_type -> alis.open.flows.v1.Flow
	7,  // 24: alis.open.flows.v1.FlowsService.GenerateFlowTree:output_type -> alis.open.flows.v1.GenerateFlowTreeResponse
	13, // 25: alis.open.flows.v1.FlowsService.HandleEvent:output_type -> google.protobuf.Empty
	13, // 26: alis.open.flows.v1.FlowsService.HandleDeadLetter:output_type -> google.protobuf.Empty
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_alis_open_flows_v1_flows_proto_init() }
func file_alis_open_flows_v1_flows_proto_init() {
	if File_alis_open_flows_v1_flows_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_open_flows_v1_flows_proto_rawDesc), len(file_alis_open_flows_v1_flows_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alis_open_flows_v1_flows_proto_goTypes,
		DependencyIndexes: file_alis_open_flows_v1_flows_proto_depIdxs,
		EnumInfos:         file_alis_open_flows_v1_flows_proto_enumTypes,
		MessageInfos:      file_alis_open_flows_v1_flows_proto_msgTypes,
	}.Build()
	File_alis_open_flows_v1_flows_proto = out.File
	file_alis_open_flows_v1_flows_proto_goTypes = nil
	file_alis_open_flows_v1_flows_proto_depIdxs = nil
}
