// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/a2a/extension/history/v1/history.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-02 09:22:52 UTC

package history

const (
	// ThreadService_GetIamPolicy_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.GetIamPolicy method.
	ThreadService_GetIamPolicy_FullMethodDescription = ""
	// ThreadService_SetIamPolicy_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.SetIamPolicy method.
	ThreadService_SetIamPolicy_FullMethodDescription = ""
	// ThreadService_AddIamBindings_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.AddIamBindings method.
	ThreadService_AddIamBindings_FullMethodDescription = ""
	// ThreadService_RemoveIamBindings_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.RemoveIamBindings method.
	ThreadService_RemoveIamBindings_FullMethodDescription = ""
	// ThreadService_ListThreads_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.ListThreads method.
	ThreadService_ListThreads_FullMethodDescription = ""
	// ThreadService_GetThread_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.GetThread method.
	ThreadService_GetThread_FullMethodDescription = ""
	// ThreadService_DeleteThread_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.DeleteThread method.
	ThreadService_DeleteThread_FullMethodDescription = ""
	// ThreadService_AppendThreadEvent_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.AppendThreadEvent method.
	ThreadService_AppendThreadEvent_FullMethodDescription = ""
	// ThreadService_GetUserThreadState_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.GetUserThreadState method.
	ThreadService_GetUserThreadState_FullMethodDescription = ""
	// ThreadService_UpdateUserThreadState_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.UpdateUserThreadState method.
	ThreadService_UpdateUserThreadState_FullMethodDescription = ""
	// ThreadService_ListThreadEvents_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.ListThreadEvents method.
	ThreadService_ListThreadEvents_FullMethodDescription = ""
	// ThreadService_StreamThreadEvents_FullMethodDescription returns the description of the alis.a2a.extension.history.v1.ThreadService.StreamThreadEvents method.
	ThreadService_StreamThreadEvents_FullMethodDescription = ""
)
