// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/a2a/extension/scheduler/v1/scheduler.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-02 09:24:23 UTC

package scheduler

const (
	// SchedulerService_CreateCron_FullMethodDescription returns the description of the alis.a2a.extension.scheduler.v1.SchedulerService.CreateCron method.
	SchedulerService_CreateCron_FullMethodDescription = ""
	// SchedulerService_ListCrons_FullMethodDescription returns the description of the alis.a2a.extension.scheduler.v1.SchedulerService.ListCrons method.
	SchedulerService_ListCrons_FullMethodDescription = ""
	// SchedulerService_GetCron_FullMethodDescription returns the description of the alis.a2a.extension.scheduler.v1.SchedulerService.GetCron method.
	SchedulerService_GetCron_FullMethodDescription = ""
	// SchedulerService_UpdateCron_FullMethodDescription returns the description of the alis.a2a.extension.scheduler.v1.SchedulerService.UpdateCron method.
	SchedulerService_UpdateCron_FullMethodDescription = ""
	// SchedulerService_DeleteCron_FullMethodDescription returns the description of the alis.a2a.extension.scheduler.v1.SchedulerService.DeleteCron method.
	SchedulerService_DeleteCron_FullMethodDescription = ""
	// SchedulerService_RunCron_FullMethodDescription returns the description of the alis.a2a.extension.scheduler.v1.SchedulerService.RunCron method.
	SchedulerService_RunCron_FullMethodDescription = ""
)
