// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/validation/v1/test.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-02 09:34:38 UTC

package validation

const (
	// BookService_GetBook_FullMethodDescription returns the description of the alis.open.validation.v1.BookService.GetBook method.
	BookService_GetBook_FullMethodDescription = ""
	// BookService_CreateBook_FullMethodDescription returns the description of the alis.open.validation.v1.BookService.CreateBook method.
	BookService_CreateBook_FullMethodDescription = ""
	// BookService_UpdateBook_FullMethodDescription returns the description of the alis.open.validation.v1.BookService.UpdateBook method.
	BookService_UpdateBook_FullMethodDescription = ""
	// BookService_DeleteBook_FullMethodDescription returns the description of the alis.open.validation.v1.BookService.DeleteBook method.
	BookService_DeleteBook_FullMethodDescription = ""
	// BookService_ListBooks_FullMethodDescription returns the description of the alis.open.validation.v1.BookService.ListBooks method.
	BookService_ListBooks_FullMethodDescription = ""
)
