// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: alis/open/in/v1/in.proto

package in

import (
	cx "github.com/alis-build/public-go/alis/open/cx"
	v1 "github.com/alis-build/public-go/alis/open/px/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FigiType int32

const (
	FigiType_FIGI_TYPE_UNSPECIFIED FigiType = 0
	FigiType_GLOBAL                FigiType = 1
	FigiType_CUSTOM                FigiType = 2
)

// Enum value maps for FigiType.
var (
	FigiType_name = map[int32]string{
		0: "FIGI_TYPE_UNSPECIFIED",
		1: "GLOBAL",
		2: "CUSTOM",
	}
	FigiType_value = map[string]int32{
		"FIGI_TYPE_UNSPECIFIED": 0,
		"GLOBAL":                1,
		"CUSTOM":                2,
	}
)

func (x FigiType) Enum() *FigiType {
	p := new(FigiType)
	*p = x
	return p
}

func (x FigiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FigiType) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_open_in_v1_in_proto_enumTypes[0].Descriptor()
}

func (FigiType) Type() protoreflect.EnumType {
	return &file_alis_open_in_v1_in_proto_enumTypes[0]
}

func (x FigiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FigiType.Descriptor instead.
func (FigiType) EnumDescriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{0}
}

type Source int32

const (
	Source_SOURCE_UNSPECIFIED Source = 0
	Source_USER               Source = 1
	Source_OPENFIGI           Source = 2
	Source_PERMID             Source = 3
	Source_DATASTREAM         Source = 4
	Source_BLOOMBERG          Source = 5
	Source_ORIGINATOR         Source = 6
	Source_IEX                Source = 7
	Source_MORNINGSTAR        Source = 8
	Source_AI                 Source = 9
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "USER",
		2: "OPENFIGI",
		3: "PERMID",
		4: "DATASTREAM",
		5: "BLOOMBERG",
		6: "ORIGINATOR",
		7: "IEX",
		8: "MORNINGSTAR",
		9: "AI",
	}
	Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"USER":               1,
		"OPENFIGI":           2,
		"PERMID":             3,
		"DATASTREAM":         4,
		"BLOOMBERG":          5,
		"ORIGINATOR":         6,
		"IEX":                7,
		"MORNINGSTAR":        8,
		"AI":                 9,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_open_in_v1_in_proto_enumTypes[1].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_alis_open_in_v1_in_proto_enumTypes[1]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{1}
}

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_ACTIVE            State = 1
	State_ARCHIVED          State = 2
	State_STALE             State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACTIVE",
		2: "ARCHIVED",
		3: "STALE",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"ACTIVE":            1,
		"ARCHIVED":          2,
		"STALE":             3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_open_in_v1_in_proto_enumTypes[2].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_alis_open_in_v1_in_proto_enumTypes[2]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{2}
}

type Instrument_MarketSector int32

const (
	Instrument_MARKET_SECTOR_UNSPECIFIED Instrument_MarketSector = 0
	Instrument_COMMODITY                 Instrument_MarketSector = 1
	Instrument_CORPORATE                 Instrument_MarketSector = 2
	Instrument_CURRENCY                  Instrument_MarketSector = 3
	Instrument_EQUITY                    Instrument_MarketSector = 4
	Instrument_INDEX                     Instrument_MarketSector = 5
	Instrument_MONEY_MARKET              Instrument_MarketSector = 6
	Instrument_GOVERNMENT                Instrument_MarketSector = 7
	Instrument_MTGE                      Instrument_MarketSector = 8
	Instrument_MUNI                      Instrument_MarketSector = 9
	Instrument_PFD                       Instrument_MarketSector = 10
)

// Enum value maps for Instrument_MarketSector.
var (
	Instrument_MarketSector_name = map[int32]string{
		0:  "MARKET_SECTOR_UNSPECIFIED",
		1:  "COMMODITY",
		2:  "CORPORATE",
		3:  "CURRENCY",
		4:  "EQUITY",
		5:  "INDEX",
		6:  "MONEY_MARKET",
		7:  "GOVERNMENT",
		8:  "MTGE",
		9:  "MUNI",
		10: "PFD",
	}
	Instrument_MarketSector_value = map[string]int32{
		"MARKET_SECTOR_UNSPECIFIED": 0,
		"COMMODITY":                 1,
		"CORPORATE":                 2,
		"CURRENCY":                  3,
		"EQUITY":                    4,
		"INDEX":                     5,
		"MONEY_MARKET":              6,
		"GOVERNMENT":                7,
		"MTGE":                      8,
		"MUNI":                      9,
		"PFD":                       10,
	}
)

func (x Instrument_MarketSector) Enum() *Instrument_MarketSector {
	p := new(Instrument_MarketSector)
	*p = x
	return p
}

func (x Instrument_MarketSector) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instrument_MarketSector) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_open_in_v1_in_proto_enumTypes[3].Descriptor()
}

func (Instrument_MarketSector) Type() protoreflect.EnumType {
	return &file_alis_open_in_v1_in_proto_enumTypes[3]
}

func (x Instrument_MarketSector) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instrument_MarketSector.Descriptor instead.
func (Instrument_MarketSector) EnumDescriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{0, 0}
}

type Instrument struct {
	state               protoimpl.MessageState                `protogen:"open.v1"`
	Name                string                                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FigiType            FigiType                              `protobuf:"varint,2,opt,name=figi_type,json=figiType,proto3,enum=alis.open.in.v1.FigiType" json:"figi_type,omitempty"`
	DisplayName         string                                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description         string                                `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MarketSector        Instrument_MarketSector               `protobuf:"varint,5,opt,name=market_sector,json=marketSector,proto3,enum=alis.open.in.v1.Instrument_MarketSector" json:"market_sector,omitempty"`
	SecurityType        string                                `protobuf:"bytes,6,opt,name=security_type,json=securityType,proto3" json:"security_type,omitempty"`
	Classifications     *Instrument_Classifications           `protobuf:"bytes,7,opt,name=classifications,proto3" json:"classifications,omitempty"`
	ExternalIds         *Instrument_ExternalIDs               `protobuf:"bytes,8,opt,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty"`
	ExchCode            string                                `protobuf:"bytes,9,opt,name=exch_code,json=exchCode,proto3" json:"exch_code,omitempty"`
	CurrencyCode        string                                `protobuf:"bytes,10,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CountryCode         string                                `protobuf:"bytes,11,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Issuer              string                                `protobuf:"bytes,12,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Ticker              string                                `protobuf:"bytes,15,opt,name=ticker,proto3" json:"ticker,omitempty"`
	WebsiteUri          string                                `protobuf:"bytes,17,opt,name=website_uri,json=websiteUri,proto3" json:"website_uri,omitempty"`
	IsCompositeFigi     bool                                  `protobuf:"varint,18,opt,name=is_composite_figi,json=isCompositeFigi,proto3" json:"is_composite_figi,omitempty"`
	IsShareClassFigi    bool                                  `protobuf:"varint,19,opt,name=is_share_class_figi,json=isShareClassFigi,proto3" json:"is_share_class_figi,omitempty"`
	UpdateTime          *timestamppb.Timestamp                `protobuf:"bytes,20,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ExchangeIdentifiers *Instrument_ExchangeIdentifiers       `protobuf:"bytes,22,opt,name=exchange_identifiers,json=exchangeIdentifiers,proto3" json:"exchange_identifiers,omitempty"`
	Engines             *Instrument_Engines                   `protobuf:"bytes,23,opt,name=engines,proto3" json:"engines,omitempty"`
	CustomAttributes    map[string]string                     `protobuf:"bytes,24,rep,name=custom_attributes,json=customAttributes,proto3" json:"custom_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SourceMeta          map[string]*Instrument_SourceMetaData `protobuf:"bytes,99,rep,name=source_meta,json=sourceMeta,proto3" json:"source_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Instrument) Reset() {
	*x = Instrument{}
	mi := &file_alis_open_in_v1_in_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument) ProtoMessage() {}

func (x *Instrument) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_in_v1_in_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument.ProtoReflect.Descriptor instead.
func (*Instrument) Descriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{0}
}

func (x *Instrument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instrument) GetFigiType() FigiType {
	if x != nil {
		return x.FigiType
	}
	return FigiType_FIGI_TYPE_UNSPECIFIED
}

func (x *Instrument) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Instrument) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Instrument) GetMarketSector() Instrument_MarketSector {
	if x != nil {
		return x.MarketSector
	}
	return Instrument_MARKET_SECTOR_UNSPECIFIED
}

func (x *Instrument) GetSecurityType() string {
	if x != nil {
		return x.SecurityType
	}
	return ""
}

func (x *Instrument) GetClassifications() *Instrument_Classifications {
	if x != nil {
		return x.Classifications
	}
	return nil
}

func (x *Instrument) GetExternalIds() *Instrument_ExternalIDs {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *Instrument) GetExchCode() string {
	if x != nil {
		return x.ExchCode
	}
	return ""
}

func (x *Instrument) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Instrument) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Instrument) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Instrument) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Instrument) GetWebsiteUri() string {
	if x != nil {
		return x.WebsiteUri
	}
	return ""
}

func (x *Instrument) GetIsCompositeFigi() bool {
	if x != nil {
		return x.IsCompositeFigi
	}
	return false
}

func (x *Instrument) GetIsShareClassFigi() bool {
	if x != nil {
		return x.IsShareClassFigi
	}
	return false
}

func (x *Instrument) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Instrument) GetExchangeIdentifiers() *Instrument_ExchangeIdentifiers {
	if x != nil {
		return x.ExchangeIdentifiers
	}
	return nil
}

func (x *Instrument) GetEngines() *Instrument_Engines {
	if x != nil {
		return x.Engines
	}
	return nil
}

func (x *Instrument) GetCustomAttributes() map[string]string {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

func (x *Instrument) GetSourceMeta() map[string]*Instrument_SourceMetaData {
	if x != nil {
		return x.SourceMeta
	}
	return nil
}

type Instrument_Classifications struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	BloombergIndustrySector   string                 `protobuf:"bytes,1,opt,name=bloomberg_industry_sector,json=bloombergIndustrySector,proto3" json:"bloomberg_industry_sector,omitempty"`
	BloombergIndustryGroup    string                 `protobuf:"bytes,2,opt,name=bloomberg_industry_group,json=bloombergIndustryGroup,proto3" json:"bloomberg_industry_group,omitempty"`
	BloombergIndustrySubgroup string                 `protobuf:"bytes,3,opt,name=bloomberg_industry_subgroup,json=bloombergIndustrySubgroup,proto3" json:"bloomberg_industry_subgroup,omitempty"`
	GicsSector                string                 `protobuf:"bytes,4,opt,name=gics_sector,json=gicsSector,proto3" json:"gics_sector,omitempty"`
	GicsIndustry              string                 `protobuf:"bytes,5,opt,name=gics_industry,json=gicsIndustry,proto3" json:"gics_industry,omitempty"`
	GicsSubindustry           string                 `protobuf:"bytes,6,opt,name=gics_subindustry,json=gicsSubindustry,proto3" json:"gics_subindustry,omitempty"`
	Theme                     string                 `protobuf:"bytes,7,opt,name=theme,proto3" json:"theme,omitempty"`
	Sector                    string                 `protobuf:"bytes,8,opt,name=sector,proto3" json:"sector,omitempty"`
	Industry                  string                 `protobuf:"bytes,9,opt,name=industry,proto3" json:"industry,omitempty"`
	MorningstarSector         string                 `protobuf:"bytes,10,opt,name=morningstar_sector,json=morningstarSector,proto3" json:"morningstar_sector,omitempty"`
	MorningstarIndustryGroup  string                 `protobuf:"bytes,11,opt,name=morningstar_industry_group,json=morningstarIndustryGroup,proto3" json:"morningstar_industry_group,omitempty"`
	MorningstarIndustry       string                 `protobuf:"bytes,12,opt,name=morningstar_industry,json=morningstarIndustry,proto3" json:"morningstar_industry,omitempty"`
	IcbIndustry               string                 `protobuf:"bytes,13,opt,name=icb_industry,json=icbIndustry,proto3" json:"icb_industry,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Instrument_Classifications) Reset() {
	*x = Instrument_Classifications{}
	mi := &file_alis_open_in_v1_in_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument_Classifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument_Classifications) ProtoMessage() {}

func (x *Instrument_Classifications) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_in_v1_in_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument_Classifications.ProtoReflect.Descriptor instead.
func (*Instrument_Classifications) Descriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Instrument_Classifications) GetBloombergIndustrySector() string {
	if x != nil {
		return x.BloombergIndustrySector
	}
	return ""
}

func (x *Instrument_Classifications) GetBloombergIndustryGroup() string {
	if x != nil {
		return x.BloombergIndustryGroup
	}
	return ""
}

func (x *Instrument_Classifications) GetBloombergIndustrySubgroup() string {
	if x != nil {
		return x.BloombergIndustrySubgroup
	}
	return ""
}

func (x *Instrument_Classifications) GetGicsSector() string {
	if x != nil {
		return x.GicsSector
	}
	return ""
}

func (x *Instrument_Classifications) GetGicsIndustry() string {
	if x != nil {
		return x.GicsIndustry
	}
	return ""
}

func (x *Instrument_Classifications) GetGicsSubindustry() string {
	if x != nil {
		return x.GicsSubindustry
	}
	return ""
}

func (x *Instrument_Classifications) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *Instrument_Classifications) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Instrument_Classifications) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *Instrument_Classifications) GetMorningstarSector() string {
	if x != nil {
		return x.MorningstarSector
	}
	return ""
}

func (x *Instrument_Classifications) GetMorningstarIndustryGroup() string {
	if x != nil {
		return x.MorningstarIndustryGroup
	}
	return ""
}

func (x *Instrument_Classifications) GetMorningstarIndustry() string {
	if x != nil {
		return x.MorningstarIndustry
	}
	return ""
}

func (x *Instrument_Classifications) GetIcbIndustry() string {
	if x != nil {
		return x.IcbIndustry
	}
	return ""
}

type Instrument_ExternalIDs struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Figi                    string                 `protobuf:"bytes,1,opt,name=figi,proto3" json:"figi,omitempty"`
	CompositeFigi           string                 `protobuf:"bytes,2,opt,name=composite_figi,json=compositeFigi,proto3" json:"composite_figi,omitempty"`
	ShareClassFigi          string                 `protobuf:"bytes,3,opt,name=share_class_figi,json=shareClassFigi,proto3" json:"share_class_figi,omitempty"`
	Isin                    string                 `protobuf:"bytes,4,opt,name=isin,proto3" json:"isin,omitempty"`
	Sedol                   string                 `protobuf:"bytes,5,opt,name=sedol,proto3" json:"sedol,omitempty"`
	Cusip                   string                 `protobuf:"bytes,6,opt,name=cusip,proto3" json:"cusip,omitempty"`
	Ric                     string                 `protobuf:"bytes,7,opt,name=ric,proto3" json:"ric,omitempty"`
	PrimaryRic              string                 `protobuf:"bytes,8,opt,name=primary_ric,json=primaryRic,proto3" json:"primary_ric,omitempty"`
	BloombergTicker         string                 `protobuf:"bytes,9,opt,name=bloomberg_ticker,json=bloombergTicker,proto3" json:"bloomberg_ticker,omitempty"`
	MsciSecCode             string                 `protobuf:"bytes,10,opt,name=msci_sec_code,json=msciSecCode,proto3" json:"msci_sec_code,omitempty"`
	Cik                     string                 `protobuf:"bytes,11,opt,name=cik,proto3" json:"cik,omitempty"`
	InvestOne               string                 `protobuf:"bytes,12,opt,name=invest_one,json=investOne,proto3" json:"invest_one,omitempty"`
	MorningstarSecId        string                 `protobuf:"bytes,13,opt,name=morningstar_sec_id,json=morningstarSecId,proto3" json:"morningstar_sec_id,omitempty"`
	MorningstarCompanyId    string                 `protobuf:"bytes,14,opt,name=morningstar_company_id,json=morningstarCompanyId,proto3" json:"morningstar_company_id,omitempty"`
	Mch                     string                 `protobuf:"bytes,15,opt,name=mch,proto3" json:"mch,omitempty"`
	Multifonds              string                 `protobuf:"bytes,16,opt,name=multifonds,proto3" json:"multifonds,omitempty"`
	Fundamental             string                 `protobuf:"bytes,17,opt,name=fundamental,proto3" json:"fundamental,omitempty"`
	MorganStanley           string                 `protobuf:"bytes,18,opt,name=morgan_stanley,json=morganStanley,proto3" json:"morgan_stanley,omitempty"`
	JseAlphaCode            string                 `protobuf:"bytes,19,opt,name=jse_alpha_code,json=jseAlphaCode,proto3" json:"jse_alpha_code,omitempty"`
	PermId                  string                 `protobuf:"bytes,20,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`
	DatastreamSymbol        string                 `protobuf:"bytes,21,opt,name=datastream_symbol,json=datastreamSymbol,proto3" json:"datastream_symbol,omitempty"`
	IexId                   string                 `protobuf:"bytes,22,opt,name=iex_id,json=iexId,proto3" json:"iex_id,omitempty"`
	PortfolioExchangeBranch string                 `protobuf:"bytes,23,opt,name=portfolio_exchange_branch,json=portfolioExchangeBranch,proto3" json:"portfolio_exchange_branch,omitempty"`
	ResearchFigi            string                 `protobuf:"bytes,24,opt,name=research_figi,json=researchFigi,proto3" json:"research_figi,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Instrument_ExternalIDs) Reset() {
	*x = Instrument_ExternalIDs{}
	mi := &file_alis_open_in_v1_in_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument_ExternalIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument_ExternalIDs) ProtoMessage() {}

func (x *Instrument_ExternalIDs) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_in_v1_in_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument_ExternalIDs.ProtoReflect.Descriptor instead.
func (*Instrument_ExternalIDs) Descriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Instrument_ExternalIDs) GetFigi() string {
	if x != nil {
		return x.Figi
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetCompositeFigi() string {
	if x != nil {
		return x.CompositeFigi
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetShareClassFigi() string {
	if x != nil {
		return x.ShareClassFigi
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetSedol() string {
	if x != nil {
		return x.Sedol
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetCusip() string {
	if x != nil {
		return x.Cusip
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetRic() string {
	if x != nil {
		return x.Ric
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetPrimaryRic() string {
	if x != nil {
		return x.PrimaryRic
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetBloombergTicker() string {
	if x != nil {
		return x.BloombergTicker
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetMsciSecCode() string {
	if x != nil {
		return x.MsciSecCode
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetCik() string {
	if x != nil {
		return x.Cik
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetInvestOne() string {
	if x != nil {
		return x.InvestOne
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetMorningstarSecId() string {
	if x != nil {
		return x.MorningstarSecId
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetMorningstarCompanyId() string {
	if x != nil {
		return x.MorningstarCompanyId
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetMch() string {
	if x != nil {
		return x.Mch
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetMultifonds() string {
	if x != nil {
		return x.Multifonds
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetFundamental() string {
	if x != nil {
		return x.Fundamental
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetMorganStanley() string {
	if x != nil {
		return x.MorganStanley
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetJseAlphaCode() string {
	if x != nil {
		return x.JseAlphaCode
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetPermId() string {
	if x != nil {
		return x.PermId
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetDatastreamSymbol() string {
	if x != nil {
		return x.DatastreamSymbol
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetIexId() string {
	if x != nil {
		return x.IexId
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetPortfolioExchangeBranch() string {
	if x != nil {
		return x.PortfolioExchangeBranch
	}
	return ""
}

func (x *Instrument_ExternalIDs) GetResearchFigi() string {
	if x != nil {
		return x.ResearchFigi
	}
	return ""
}

type Instrument_ExchangeIdentifiers struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Mic                     string                 `protobuf:"bytes,1,opt,name=mic,proto3" json:"mic,omitempty"`
	OperatingMic            string                 `protobuf:"bytes,12,opt,name=operating_mic,json=operatingMic,proto3" json:"operating_mic,omitempty"`
	BloombergExchangeCode   string                 `protobuf:"bytes,2,opt,name=bloomberg_exchange_code,json=bloombergExchangeCode,proto3" json:"bloomberg_exchange_code,omitempty"`
	MorningstarExchangeCode string                 `protobuf:"bytes,3,opt,name=morningstar_exchange_code,json=morningstarExchangeCode,proto3" json:"morningstar_exchange_code,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Instrument_ExchangeIdentifiers) Reset() {
	*x = Instrument_ExchangeIdentifiers{}
	mi := &file_alis_open_in_v1_in_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument_ExchangeIdentifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument_ExchangeIdentifiers) ProtoMessage() {}

func (x *Instrument_ExchangeIdentifiers) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_in_v1_in_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument_ExchangeIdentifiers.ProtoReflect.Descriptor instead.
func (*Instrument_ExchangeIdentifiers) Descriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Instrument_ExchangeIdentifiers) GetMic() string {
	if x != nil {
		return x.Mic
	}
	return ""
}

func (x *Instrument_ExchangeIdentifiers) GetOperatingMic() string {
	if x != nil {
		return x.OperatingMic
	}
	return ""
}

func (x *Instrument_ExchangeIdentifiers) GetBloombergExchangeCode() string {
	if x != nil {
		return x.BloombergExchangeCode
	}
	return ""
}

func (x *Instrument_ExchangeIdentifiers) GetMorningstarExchangeCode() string {
	if x != nil {
		return x.MorningstarExchangeCode
	}
	return ""
}

type Instrument_Engines struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Px            *v1.Instrument         `protobuf:"bytes,1,opt,name=px,proto3" json:"px,omitempty"`
	Cx            *cx.Instrument         `protobuf:"bytes,2,opt,name=cx,proto3" json:"cx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instrument_Engines) Reset() {
	*x = Instrument_Engines{}
	mi := &file_alis_open_in_v1_in_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument_Engines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument_Engines) ProtoMessage() {}

func (x *Instrument_Engines) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_in_v1_in_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument_Engines.ProtoReflect.Descriptor instead.
func (*Instrument_Engines) Descriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Instrument_Engines) GetPx() *v1.Instrument {
	if x != nil {
		return x.Px
	}
	return nil
}

func (x *Instrument_Engines) GetCx() *cx.Instrument {
	if x != nil {
		return x.Cx
	}
	return nil
}

type Instrument_SourceMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        Source                 `protobuf:"varint,1,opt,name=source,proto3,enum=alis.open.in.v1.Source" json:"source,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instrument_SourceMetaData) Reset() {
	*x = Instrument_SourceMetaData{}
	mi := &file_alis_open_in_v1_in_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument_SourceMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument_SourceMetaData) ProtoMessage() {}

func (x *Instrument_SourceMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_alis_open_in_v1_in_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument_SourceMetaData.ProtoReflect.Descriptor instead.
func (*Instrument_SourceMetaData) Descriptor() ([]byte, []int) {
	return file_alis_open_in_v1_in_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Instrument_SourceMetaData) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *Instrument_SourceMetaData) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_alis_open_in_v1_in_proto protoreflect.FileDescriptor

const file_alis_open_in_v1_in_proto_rawDesc = "" +
	"\n" +
	"\x18alis/open/in/v1/in.proto\x12\x0falis.open.in.v1\x1a\x18alis/open/cx/v1/cx.proto\x1a\x18alis/open/px/v1/px.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x19\n" +
	"\n" +
	"Instrument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\tfigi_type\x18\x02 \x01(\x0e2\x19.alis.open.in.v1.FigiTypeR\bfigiType\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12M\n" +
	"\rmarket_sector\x18\x05 \x01(\x0e2(.alis.open.in.v1.Instrument.MarketSectorR\fmarketSector\x12#\n" +
	"\rsecurity_type\x18\x06 \x01(\tR\fsecurityType\x12U\n" +
	"\x0fclassifications\x18\a \x01(\v2+.alis.open.in.v1.Instrument.ClassificationsR\x0fclassifications\x12J\n" +
	"\fexternal_ids\x18\b \x01(\v2'.alis.open.in.v1.Instrument.ExternalIDsR\vexternalIds\x12\x1b\n" +
	"\texch_code\x18\t \x01(\tR\bexchCode\x12#\n" +
	"\rcurrency_code\x18\n" +
	" \x01(\tR\fcurrencyCode\x12!\n" +
	"\fcountry_code\x18\v \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06issuer\x18\f \x01(\tR\x06issuer\x12\x16\n" +
	"\x06ticker\x18\x0f \x01(\tR\x06ticker\x12\x1f\n" +
	"\vwebsite_uri\x18\x11 \x01(\tR\n" +
	"websiteUri\x12*\n" +
	"\x11is_composite_figi\x18\x12 \x01(\bR\x0fisCompositeFigi\x12-\n" +
	"\x13is_share_class_figi\x18\x13 \x01(\bR\x10isShareClassFigi\x12;\n" +
	"\vupdate_time\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12b\n" +
	"\x14exchange_identifiers\x18\x16 \x01(\v2/.alis.open.in.v1.Instrument.ExchangeIdentifiersR\x13exchangeIdentifiers\x12=\n" +
	"\aengines\x18\x17 \x01(\v2#.alis.open.in.v1.Instrument.EnginesR\aengines\x12^\n" +
	"\x11custom_attributes\x18\x18 \x03(\v21.alis.open.in.v1.Instrument.CustomAttributesEntryR\x10customAttributes\x12L\n" +
	"\vsource_meta\x18c \x03(\v2+.alis.open.in.v1.Instrument.SourceMetaEntryR\n" +
	"sourceMeta\x1a\xc5\x04\n" +
	"\x0fClassifications\x12:\n" +
	"\x19bloomberg_industry_sector\x18\x01 \x01(\tR\x17bloombergIndustrySector\x128\n" +
	"\x18bloomberg_industry_group\x18\x02 \x01(\tR\x16bloombergIndustryGroup\x12>\n" +
	"\x1bbloomberg_industry_subgroup\x18\x03 \x01(\tR\x19bloombergIndustrySubgroup\x12\x1f\n" +
	"\vgics_sector\x18\x04 \x01(\tR\n" +
	"gicsSector\x12#\n" +
	"\rgics_industry\x18\x05 \x01(\tR\fgicsIndustry\x12)\n" +
	"\x10gics_subindustry\x18\x06 \x01(\tR\x0fgicsSubindustry\x12\x14\n" +
	"\x05theme\x18\a \x01(\tR\x05theme\x12\x16\n" +
	"\x06sector\x18\b \x01(\tR\x06sector\x12\x1a\n" +
	"\bindustry\x18\t \x01(\tR\bindustry\x12-\n" +
	"\x12morningstar_sector\x18\n" +
	" \x01(\tR\x11morningstarSector\x12<\n" +
	"\x1amorningstar_industry_group\x18\v \x01(\tR\x18morningstarIndustryGroup\x121\n" +
	"\x14morningstar_industry\x18\f \x01(\tR\x13morningstarIndustry\x12!\n" +
	"\ficb_industry\x18\r \x01(\tR\vicbIndustry\x1a\xa8\x06\n" +
	"\vExternalIDs\x12\x12\n" +
	"\x04figi\x18\x01 \x01(\tR\x04figi\x12%\n" +
	"\x0ecomposite_figi\x18\x02 \x01(\tR\rcompositeFigi\x12(\n" +
	"\x10share_class_figi\x18\x03 \x01(\tR\x0eshareClassFigi\x12\x12\n" +
	"\x04isin\x18\x04 \x01(\tR\x04isin\x12\x14\n" +
	"\x05sedol\x18\x05 \x01(\tR\x05sedol\x12\x14\n" +
	"\x05cusip\x18\x06 \x01(\tR\x05cusip\x12\x10\n" +
	"\x03ric\x18\a \x01(\tR\x03ric\x12\x1f\n" +
	"\vprimary_ric\x18\b \x01(\tR\n" +
	"primaryRic\x12)\n" +
	"\x10bloomberg_ticker\x18\t \x01(\tR\x0fbloombergTicker\x12\"\n" +
	"\rmsci_sec_code\x18\n" +
	" \x01(\tR\vmsciSecCode\x12\x10\n" +
	"\x03cik\x18\v \x01(\tR\x03cik\x12\x1d\n" +
	"\n" +
	"invest_one\x18\f \x01(\tR\tinvestOne\x12,\n" +
	"\x12morningstar_sec_id\x18\r \x01(\tR\x10morningstarSecId\x124\n" +
	"\x16morningstar_company_id\x18\x0e \x01(\tR\x14morningstarCompanyId\x12\x10\n" +
	"\x03mch\x18\x0f \x01(\tR\x03mch\x12\x1e\n" +
	"\n" +
	"multifonds\x18\x10 \x01(\tR\n" +
	"multifonds\x12 \n" +
	"\vfundamental\x18\x11 \x01(\tR\vfundamental\x12%\n" +
	"\x0emorgan_stanley\x18\x12 \x01(\tR\rmorganStanley\x12$\n" +
	"\x0ejse_alpha_code\x18\x13 \x01(\tR\fjseAlphaCode\x12\x17\n" +
	"\aperm_id\x18\x14 \x01(\tR\x06permId\x12+\n" +
	"\x11datastream_symbol\x18\x15 \x01(\tR\x10datastreamSymbol\x12\x15\n" +
	"\x06iex_id\x18\x16 \x01(\tR\x05iexId\x12:\n" +
	"\x19portfolio_exchange_branch\x18\x17 \x01(\tR\x17portfolioExchangeBranch\x12#\n" +
	"\rresearch_figi\x18\x18 \x01(\tR\fresearchFigi\x1a\xc0\x01\n" +
	"\x13ExchangeIdentifiers\x12\x10\n" +
	"\x03mic\x18\x01 \x01(\tR\x03mic\x12#\n" +
	"\roperating_mic\x18\f \x01(\tR\foperatingMic\x126\n" +
	"\x17bloomberg_exchange_code\x18\x02 \x01(\tR\x15bloombergExchangeCode\x12:\n" +
	"\x19morningstar_exchange_code\x18\x03 \x01(\tR\x17morningstarExchangeCode\x1ac\n" +
	"\aEngines\x12+\n" +
	"\x02px\x18\x01 \x01(\v2\x1b.alis.open.px.v1.InstrumentR\x02px\x12+\n" +
	"\x02cx\x18\x02 \x01(\v2\x1b.alis.open.cx.v1.InstrumentR\x02cx\x1aC\n" +
	"\x15CustomAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ai\n" +
	"\x0fSourceMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.alis.open.in.v1.Instrument.SourceMetaDataR\x05value:\x028\x01\x1a~\n" +
	"\x0eSourceMetaData\x12/\n" +
	"\x06source\x18\x01 \x01(\x0e2\x17.alis.open.in.v1.SourceR\x06source\x12;\n" +
	"\vupdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xaf\x01\n" +
	"\fMarketSector\x12\x1d\n" +
	"\x19MARKET_SECTOR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOMMODITY\x10\x01\x12\r\n" +
	"\tCORPORATE\x10\x02\x12\f\n" +
	"\bCURRENCY\x10\x03\x12\n" +
	"\n" +
	"\x06EQUITY\x10\x04\x12\t\n" +
	"\x05INDEX\x10\x05\x12\x10\n" +
	"\fMONEY_MARKET\x10\x06\x12\x0e\n" +
	"\n" +
	"GOVERNMENT\x10\a\x12\b\n" +
	"\x04MTGE\x10\b\x12\b\n" +
	"\x04MUNI\x10\t\x12\a\n" +
	"\x03PFD\x10\n" +
	"J\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x10\x10\x11J\x04\b\x15\x10\x16*=\n" +
	"\bFigiType\x12\x19\n" +
	"\x15FIGI_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x01\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x02*\x95\x01\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\f\n" +
	"\bOPENFIGI\x10\x02\x12\n" +
	"\n" +
	"\x06PERMID\x10\x03\x12\x0e\n" +
	"\n" +
	"DATASTREAM\x10\x04\x12\r\n" +
	"\tBLOOMBERG\x10\x05\x12\x0e\n" +
	"\n" +
	"ORIGINATOR\x10\x06\x12\a\n" +
	"\x03IEX\x10\a\x12\x0f\n" +
	"\vMORNINGSTAR\x10\b\x12\x06\n" +
	"\x02AI\x10\t*C\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bARCHIVED\x10\x02\x12\t\n" +
	"\x05STALE\x10\x03B.Z,github.com/alis-build/public-go/alis/open/inb\x06proto3"

var (
	file_alis_open_in_v1_in_proto_rawDescOnce sync.Once
	file_alis_open_in_v1_in_proto_rawDescData []byte
)

func file_alis_open_in_v1_in_proto_rawDescGZIP() []byte {
	file_alis_open_in_v1_in_proto_rawDescOnce.Do(func() {
		file_alis_open_in_v1_in_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_open_in_v1_in_proto_rawDesc), len(file_alis_open_in_v1_in_proto_rawDesc)))
	})
	return file_alis_open_in_v1_in_proto_rawDescData
}

var file_alis_open_in_v1_in_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_alis_open_in_v1_in_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_alis_open_in_v1_in_proto_goTypes = []any{
	(FigiType)(0),                          // 0: alis.open.in.v1.FigiType
	(Source)(0),                            // 1: alis.open.in.v1.Source
	(State)(0),                             // 2: alis.open.in.v1.State
	(Instrument_MarketSector)(0),           // 3: alis.open.in.v1.Instrument.MarketSector
	(*Instrument)(nil),                     // 4: alis.open.in.v1.Instrument
	(*Instrument_Classifications)(nil),     // 5: alis.open.in.v1.Instrument.Classifications
	(*Instrument_ExternalIDs)(nil),         // 6: alis.open.in.v1.Instrument.ExternalIDs
	(*Instrument_ExchangeIdentifiers)(nil), // 7: alis.open.in.v1.Instrument.ExchangeIdentifiers
	(*Instrument_Engines)(nil),             // 8: alis.open.in.v1.Instrument.Engines
	nil,                                    // 9: alis.open.in.v1.Instrument.CustomAttributesEntry
	nil,                                    // 10: alis.open.in.v1.Instrument.SourceMetaEntry
	(*Instrument_SourceMetaData)(nil),      // 11: alis.open.in.v1.Instrument.SourceMetaData
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
	(*v1.Instrument)(nil),                  // 13: alis.open.px.v1.Instrument
	(*cx.Instrument)(nil),                  // 14: alis.open.cx.v1.Instrument
}
var file_alis_open_in_v1_in_proto_depIdxs = []int32{
	0,  // 0: alis.open.in.v1.Instrument.figi_type:type_name -> alis.open.in.v1.FigiType
	3,  // 1: alis.open.in.v1.Instrument.market_sector:type_name -> alis.open.in.v1.Instrument.MarketSector
	5,  // 2: alis.open.in.v1.Instrument.classifications:type_name -> alis.open.in.v1.Instrument.Classifications
	6,  // 3: alis.open.in.v1.Instrument.external_ids:type_name -> alis.open.in.v1.Instrument.ExternalIDs
	12, // 4: alis.open.in.v1.Instrument.update_time:type_name -> google.protobuf.Timestamp
	7,  // 5: alis.open.in.v1.Instrument.exchange_identifiers:type_name -> alis.open.in.v1.Instrument.ExchangeIdentifiers
	8,  // 6: alis.open.in.v1.Instrument.engines:type_name -> alis.open.in.v1.Instrument.Engines
	9,  // 7: alis.open.in.v1.Instrument.custom_attributes:type_name -> alis.open.in.v1.Instrument.CustomAttributesEntry
	10, // 8: alis.open.in.v1.Instrument.source_meta:type_name -> alis.open.in.v1.Instrument.SourceMetaEntry
	13, // 9: alis.open.in.v1.Instrument.Engines.px:type_name -> alis.open.px.v1.Instrument
	14, // 10: alis.open.in.v1.Instrument.Engines.cx:type_name -> alis.open.cx.v1.Instrument
	11, // 11: alis.open.in.v1.Instrument.SourceMetaEntry.value:type_name -> alis.open.in.v1.Instrument.SourceMetaData
	1,  // 12: alis.open.in.v1.Instrument.SourceMetaData.source:type_name -> alis.open.in.v1.Source
	12, // 13: alis.open.in.v1.Instrument.SourceMetaData.update_time:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_alis_open_in_v1_in_proto_init() }
func file_alis_open_in_v1_in_proto_init() {
	if File_alis_open_in_v1_in_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_open_in_v1_in_proto_rawDesc), len(file_alis_open_in_v1_in_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_open_in_v1_in_proto_goTypes,
		DependencyIndexes: file_alis_open_in_v1_in_proto_depIdxs,
		EnumInfos:         file_alis_open_in_v1_in_proto_enumTypes,
		MessageInfos:      file_alis_open_in_v1_in_proto_msgTypes,
	}.Build()
	File_alis_open_in_v1_in_proto = out.File
	file_alis_open_in_v1_in_proto_goTypes = nil
	file_alis_open_in_v1_in_proto_depIdxs = nil
}
