// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/notifications/v1/devices.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-06-24 12:06:20 UTC

package v1

const (
	// DevicesService_ValidateMessage_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.ValidateMessage method.
	DevicesService_ValidateMessage_FullMethodDescription = ""
	// DevicesService_RetrieveRules_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.RetrieveRules method.
	DevicesService_RetrieveRules_FullMethodDescription = ""
	// DevicesService_GetIamPolicy_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.GetIamPolicy method.
	DevicesService_GetIamPolicy_FullMethodDescription = ""
	// DevicesService_SetIamPolicy_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.SetIamPolicy method.
	DevicesService_SetIamPolicy_FullMethodDescription = ""
	// DevicesService_TestIamPermissions_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.TestIamPermissions method.
	DevicesService_TestIamPermissions_FullMethodDescription = ""
	// DevicesService_AddIamBindings_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.AddIamBindings method.
	DevicesService_AddIamBindings_FullMethodDescription = ""
	// DevicesService_RemoveIamBindings_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.RemoveIamBindings method.
	DevicesService_RemoveIamBindings_FullMethodDescription = ""
	// DevicesService_RegisterDevice_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.RegisterDevice method.
	DevicesService_RegisterDevice_FullMethodDescription = ""
	// DevicesService_GetDevice_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.GetDevice method.
	DevicesService_GetDevice_FullMethodDescription = ""
	// DevicesService_ListDevices_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.ListDevices method.
	DevicesService_ListDevices_FullMethodDescription = ""
	// DevicesService_DeleteDevice_FullMethodDescription returns the description of the alis.open.notifications.v1.DevicesService.DeleteDevice method.
	DevicesService_DeleteDevice_FullMethodDescription = ""
)
