// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/notifications/v1/notifications.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-06-24 12:06:20 UTC

package v1

const (
	// NotificationsService_ValidateMessage_FullMethodDescription returns the description of the alis.open.notifications.v1.NotificationsService.ValidateMessage method.
	NotificationsService_ValidateMessage_FullMethodDescription = ""
	// NotificationsService_RetrieveRules_FullMethodDescription returns the description of the alis.open.notifications.v1.NotificationsService.RetrieveRules method.
	NotificationsService_RetrieveRules_FullMethodDescription = ""
	// NotificationsService_TestIamPermissions_FullMethodDescription returns the description of the alis.open.notifications.v1.NotificationsService.TestIamPermissions method.
	NotificationsService_TestIamPermissions_FullMethodDescription = ""
	// NotificationsService_SendFcmMessage_FullMethodDescription returns the description of the alis.open.notifications.v1.NotificationsService.SendFcmMessage method.
	NotificationsService_SendFcmMessage_FullMethodDescription = ""
	// NotificationsService_BatchSendFcmMessages_FullMethodDescription returns the description of the alis.open.notifications.v1.NotificationsService.BatchSendFcmMessages method.
	NotificationsService_BatchSendFcmMessages_FullMethodDescription = ""
)
