// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/cx/v1/cx.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-02 09:30:30 UTC

package cx

const ()
