// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/agent/v2/a2a.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-06-30 11:23:12 UTC

package v2

const (
	// A2AService_SendMessage_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.SendMessage method.
	A2AService_SendMessage_FullMethodDescription = ""
	// A2AService_SendStreamingMessage_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.SendStreamingMessage method.
	A2AService_SendStreamingMessage_FullMethodDescription = ""
	// A2AService_GetTask_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.GetTask method.
	A2AService_GetTask_FullMethodDescription = ""
	// A2AService_ListTasks_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.ListTasks method.
	A2AService_ListTasks_FullMethodDescription = ""
	// A2AService_CancelTask_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.CancelTask method.
	A2AService_CancelTask_FullMethodDescription = ""
	// A2AService_TaskSubscription_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.TaskSubscription method.
	A2AService_TaskSubscription_FullMethodDescription = ""
	// A2AService_CreateTaskPushNotificationConfig_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.CreateTaskPushNotificationConfig method.
	A2AService_CreateTaskPushNotificationConfig_FullMethodDescription = ""
	// A2AService_GetTaskPushNotificationConfig_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.GetTaskPushNotificationConfig method.
	A2AService_GetTaskPushNotificationConfig_FullMethodDescription = ""
	// A2AService_ListTaskPushNotificationConfig_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.ListTaskPushNotificationConfig method.
	A2AService_ListTaskPushNotificationConfig_FullMethodDescription = ""
	// A2AService_GetAgentCard_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.GetAgentCard method.
	A2AService_GetAgentCard_FullMethodDescription = ""
	// A2AService_DeleteTaskPushNotificationConfig_FullMethodDescription returns the description of the alis.open.agent.v2.A2AService.DeleteTaskPushNotificationConfig method.
	A2AService_DeleteTaskPushNotificationConfig_FullMethodDescription = ""
)
