// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: alis/agui/history/v1/history.proto

package history

import (
	v11 "github.com/alis-build/public-go/alis/iam/v1"
	v1 "google.golang.org/genproto/googleapis/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Thread struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName      string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AgentId          string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentDisplayName string                 `protobuf:"bytes,4,opt,name=agent_display_name,json=agentDisplayName,proto3" json:"agent_display_name,omitempty"`
	RunCount         int64                  `protobuf:"varint,5,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	LastActivityTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_activity_time,json=lastActivityTime,proto3" json:"last_activity_time,omitempty"`
	CreateTime       *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *Thread) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Thread) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Thread) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Thread) GetAgentDisplayName() string {
	if x != nil {
		return x.AgentDisplayName
	}
	return ""
}

func (x *Thread) GetRunCount() int64 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *Thread) GetLastActivityTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityTime
	}
	return nil
}

func (x *Thread) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type UserThreadState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Thread        string                 `protobuf:"bytes,2,opt,name=thread,proto3" json:"thread,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	ReadRunCount  int64                  `protobuf:"varint,4,opt,name=read_run_count,json=readRunCount,proto3" json:"read_run_count,omitempty"`
	LastReadTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_read_time,json=lastReadTime,proto3" json:"last_read_time,omitempty"`
	Pinned        bool                   `protobuf:"varint,6,opt,name=pinned,proto3" json:"pinned,omitempty"`
	PinnedTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=pinned_time,json=pinnedTime,proto3" json:"pinned_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserThreadState) Reset() {
	*x = UserThreadState{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserThreadState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserThreadState) ProtoMessage() {}

func (x *UserThreadState) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserThreadState.ProtoReflect.Descriptor instead.
func (*UserThreadState) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *UserThreadState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserThreadState) GetThread() string {
	if x != nil {
		return x.Thread
	}
	return ""
}

func (x *UserThreadState) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserThreadState) GetReadRunCount() int64 {
	if x != nil {
		return x.ReadRunCount
	}
	return 0
}

func (x *UserThreadState) GetLastReadTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReadTime
	}
	return nil
}

func (x *UserThreadState) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *UserThreadState) GetPinnedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PinnedTime
	}
	return nil
}

func (x *UserThreadState) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type ThreadView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        *Thread                `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	ReadRunCount  int64                  `protobuf:"varint,2,opt,name=read_run_count,json=readRunCount,proto3" json:"read_run_count,omitempty"`
	HasUnread     bool                   `protobuf:"varint,3,opt,name=has_unread,json=hasUnread,proto3" json:"has_unread,omitempty"`
	Pinned        bool                   `protobuf:"varint,4,opt,name=pinned,proto3" json:"pinned,omitempty"`
	PinnedTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=pinned_time,json=pinnedTime,proto3" json:"pinned_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadView) Reset() {
	*x = ThreadView{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadView) ProtoMessage() {}

func (x *ThreadView) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadView.ProtoReflect.Descriptor instead.
func (*ThreadView) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *ThreadView) GetThread() *Thread {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *ThreadView) GetReadRunCount() int64 {
	if x != nil {
		return x.ReadRunCount
	}
	return 0
}

func (x *ThreadView) GetHasUnread() bool {
	if x != nil {
		return x.HasUnread
	}
	return false
}

func (x *ThreadView) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ThreadView) GetPinnedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PinnedTime
	}
	return nil
}

type ListThreadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsRequest) Reset() {
	*x = ListThreadsRequest{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsRequest) ProtoMessage() {}

func (x *ListThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListThreadsRequest) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *ListThreadsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListThreadsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListThreadsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListThreadsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ListThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*ThreadView          `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsResponse) Reset() {
	*x = ListThreadsResponse{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsResponse) ProtoMessage() {}

func (x *ListThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListThreadsResponse) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *ListThreadsResponse) GetThreads() []*ThreadView {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ListThreadsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{5}
}

func (x *GetThreadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetThreadRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type DeleteThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreadRequest) Reset() {
	*x = DeleteThreadRequest{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreadRequest) ProtoMessage() {}

func (x *DeleteThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteThreadRequest) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteThreadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserThreadStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserThreadStateRequest) Reset() {
	*x = GetUserThreadStateRequest{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserThreadStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserThreadStateRequest) ProtoMessage() {}

func (x *GetUserThreadStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserThreadStateRequest.ProtoReflect.Descriptor instead.
func (*GetUserThreadStateRequest) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserThreadStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserThreadStateRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type UpdateUserThreadStateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserThreadState *UserThreadState       `protobuf:"bytes,1,opt,name=user_thread_state,json=userThreadState,proto3" json:"user_thread_state,omitempty"`
	UpdateMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserThreadStateRequest) Reset() {
	*x = UpdateUserThreadStateRequest{}
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserThreadStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserThreadStateRequest) ProtoMessage() {}

func (x *UpdateUserThreadStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_agui_history_v1_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserThreadStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserThreadStateRequest) Descriptor() ([]byte, []int) {
	return file_alis_agui_history_v1_history_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserThreadStateRequest) GetUserThreadState() *UserThreadState {
	if x != nil {
		return x.UserThreadState
	}
	return nil
}

func (x *UpdateUserThreadStateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_alis_agui_history_v1_history_proto protoreflect.FileDescriptor

const file_alis_agui_history_v1_history_proto_rawDesc = "" +
	"\n" +
	"\"alis/agui/history/v1/history.proto\x12\x14alis.agui.history.v1\x1a\x15alis/iam/v1/iam.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x02\n" +
	"\x06Thread\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12,\n" +
	"\x12agent_display_name\x18\x04 \x01(\tR\x10agentDisplayName\x12\x1b\n" +
	"\trun_count\x18\x05 \x01(\x03R\brunCount\x12H\n" +
	"\x12last_activity_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastActivityTime\x12;\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\xcb\x02\n" +
	"\x0fUserThreadState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06thread\x18\x02 \x01(\tR\x06thread\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12$\n" +
	"\x0eread_run_count\x18\x04 \x01(\x03R\freadRunCount\x12@\n" +
	"\x0elast_read_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastReadTime\x12\x16\n" +
	"\x06pinned\x18\x06 \x01(\bR\x06pinned\x12;\n" +
	"\vpinned_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pinnedTime\x12;\n" +
	"\vupdate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xdc\x01\n" +
	"\n" +
	"ThreadView\x124\n" +
	"\x06thread\x18\x01 \x01(\v2\x1c.alis.agui.history.v1.ThreadR\x06thread\x12$\n" +
	"\x0eread_run_count\x18\x02 \x01(\x03R\freadRunCount\x12\x1d\n" +
	"\n" +
	"has_unread\x18\x03 \x01(\bR\thasUnread\x12\x16\n" +
	"\x06pinned\x18\x04 \x01(\bR\x06pinned\x12;\n" +
	"\vpinned_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pinnedTime\"\xaa\x01\n" +
	"\x12ListThreadsRequest\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x127\n" +
	"\tread_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMaskJ\x04\b\x01\x10\x02\"y\n" +
	"\x13ListThreadsResponse\x12:\n" +
	"\athreads\x18\x01 \x03(\v2 .alis.agui.history.v1.ThreadViewR\athreads\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"_\n" +
	"\x10GetThreadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\")\n" +
	"\x13DeleteThreadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"h\n" +
	"\x19GetUserThreadStateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xae\x01\n" +
	"\x1cUpdateUserThreadStateRequest\x12Q\n" +
	"\x11user_thread_state\x18\x01 \x01(\v2%.alis.agui.history.v1.UserThreadStateR\x0fuserThreadState\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask2\xc3\x06\n" +
	"\rThreadService\x12K\n" +
	"\fGetIamPolicy\x12\".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12K\n" +
	"\fSetIamPolicy\x12\".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12M\n" +
	"\x0eAddIamBindings\x12\".alis.iam.v1.AddIamBindingsRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12S\n" +
	"\x11RemoveIamBindings\x12%.alis.iam.v1.RemoveIamBindingsRequest\x1a\x15.google.iam.v1.Policy\"\x00\x12d\n" +
	"\vListThreads\x12(.alis.agui.history.v1.ListThreadsRequest\x1a).alis.agui.history.v1.ListThreadsResponse\"\x00\x12S\n" +
	"\tGetThread\x12&.alis.agui.history.v1.GetThreadRequest\x1a\x1c.alis.agui.history.v1.Thread\"\x00\x12S\n" +
	"\fDeleteThread\x12).alis.agui.history.v1.DeleteThreadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12n\n" +
	"\x12GetUserThreadState\x12/.alis.agui.history.v1.GetUserThreadStateRequest\x1a%.alis.agui.history.v1.UserThreadState\"\x00\x12t\n" +
	"\x15UpdateUserThreadState\x122.alis.agui.history.v1.UpdateUserThreadStateRequest\x1a%.alis.agui.history.v1.UserThreadState\"\x00B3Z1github.com/alis-build/public-go/alis/agui/historyb\x06proto3"

var (
	file_alis_agui_history_v1_history_proto_rawDescOnce sync.Once
	file_alis_agui_history_v1_history_proto_rawDescData []byte
)

func file_alis_agui_history_v1_history_proto_rawDescGZIP() []byte {
	file_alis_agui_history_v1_history_proto_rawDescOnce.Do(func() {
		file_alis_agui_history_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_agui_history_v1_history_proto_rawDesc), len(file_alis_agui_history_v1_history_proto_rawDesc)))
	})
	return file_alis_agui_history_v1_history_proto_rawDescData
}

var file_alis_agui_history_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_alis_agui_history_v1_history_proto_goTypes = []any{
	(*Thread)(nil),                       // 0: alis.agui.history.v1.Thread
	(*UserThreadState)(nil),              // 1: alis.agui.history.v1.UserThreadState
	(*ThreadView)(nil),                   // 2: alis.agui.history.v1.ThreadView
	(*ListThreadsRequest)(nil),           // 3: alis.agui.history.v1.ListThreadsRequest
	(*ListThreadsResponse)(nil),          // 4: alis.agui.history.v1.ListThreadsResponse
	(*GetThreadRequest)(nil),             // 5: alis.agui.history.v1.GetThreadRequest
	(*DeleteThreadRequest)(nil),          // 6: alis.agui.history.v1.DeleteThreadRequest
	(*GetUserThreadStateRequest)(nil),    // 7: alis.agui.history.v1.GetUserThreadStateRequest
	(*UpdateUserThreadStateRequest)(nil), // 8: alis.agui.history.v1.UpdateUserThreadStateRequest
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),        // 10: google.protobuf.FieldMask
	(*v1.GetIamPolicyRequest)(nil),       // 11: google.iam.v1.GetIamPolicyRequest
	(*v1.SetIamPolicyRequest)(nil),       // 12: google.iam.v1.SetIamPolicyRequest
	(*v11.AddIamBindingsRequest)(nil),    // 13: alis.iam.v1.AddIamBindingsRequest
	(*v11.RemoveIamBindingsRequest)(nil), // 14: alis.iam.v1.RemoveIamBindingsRequest
	(*v1.Policy)(nil),                    // 15: google.iam.v1.Policy
	(*emptypb.Empty)(nil),                // 16: google.protobuf.Empty
}
var file_alis_agui_history_v1_history_proto_depIdxs = []int32{
	9,  // 0: alis.agui.history.v1.Thread.last_activity_time:type_name -> google.protobuf.Timestamp
	9,  // 1: alis.agui.history.v1.Thread.create_time:type_name -> google.protobuf.Timestamp
	9,  // 2: alis.agui.history.v1.UserThreadState.last_read_time:type_name -> google.protobuf.Timestamp
	9,  // 3: alis.agui.history.v1.UserThreadState.pinned_time:type_name -> google.protobuf.Timestamp
	9,  // 4: alis.agui.history.v1.UserThreadState.update_time:type_name -> google.protobuf.Timestamp
	0,  // 5: alis.agui.history.v1.ThreadView.thread:type_name -> alis.agui.history.v1.Thread
	9,  // 6: alis.agui.history.v1.ThreadView.pinned_time:type_name -> google.protobuf.Timestamp
	10, // 7: alis.agui.history.v1.ListThreadsRequest.read_mask:type_name -> google.protobuf.FieldMask
	2,  // 8: alis.agui.history.v1.ListThreadsResponse.threads:type_name -> alis.agui.history.v1.ThreadView
	10, // 9: alis.agui.history.v1.GetThreadRequest.read_mask:type_name -> google.protobuf.FieldMask
	10, // 10: alis.agui.history.v1.GetUserThreadStateRequest.read_mask:type_name -> google.protobuf.FieldMask
	1,  // 11: alis.agui.history.v1.UpdateUserThreadStateRequest.user_thread_state:type_name -> alis.agui.history.v1.UserThreadState
	10, // 12: alis.agui.history.v1.UpdateUserThreadStateRequest.update_mask:type_name -> google.protobuf.FieldMask
	11, // 13: alis.agui.history.v1.ThreadService.GetIamPolicy:input_type -> google.iam.v1.GetIamPolicyRequest
	12, // 14: alis.agui.history.v1.ThreadService.SetIamPolicy:input_type -> google.iam.v1.SetIamPolicyRequest
	13, // 15: alis.agui.history.v1.ThreadService.AddIamBindings:input_type -> alis.iam.v1.AddIamBindingsRequest
	14, // 16: alis.agui.history.v1.ThreadService.RemoveIamBindings:input_type -> alis.iam.v1.RemoveIamBindingsRequest
	3,  // 17: alis.agui.history.v1.ThreadService.ListThreads:input_type -> alis.agui.history.v1.ListThreadsRequest
	5,  // 18: alis.agui.history.v1.ThreadService.GetThread:input_type -> alis.agui.history.v1.GetThreadRequest
	6,  // 19: alis.agui.history.v1.ThreadService.DeleteThread:input_type -> alis.agui.history.v1.DeleteThreadRequest
	7,  // 20: alis.agui.history.v1.ThreadService.GetUserThreadState:input_type -> alis.agui.history.v1.GetUserThreadStateRequest
	8,  // 21: alis.agui.history.v1.ThreadService.UpdateUserThreadState:input_type -> alis.agui.history.v1.UpdateUserThreadStateRequest
	15, // 22: alis.agui.history.v1.ThreadService.GetIamPolicy:output_type -> google.iam.v1.Policy
	15, // 23: alis.agui.history.v1.ThreadService.SetIamPolicy:output_type -> google.iam.v1.Policy
	15, // 24: alis.agui.history.v1.ThreadService.AddIamBindings:output_type -> google.iam.v1.Policy
	15, // 25: alis.agui.history.v1.ThreadService.RemoveIamBindings:output_type -> google.iam.v1.Policy
	4,  // 26: alis.agui.history.v1.ThreadService.ListThreads:output_type -> alis.agui.history.v1.ListThreadsResponse
	0,  // 27: alis.agui.history.v1.ThreadService.GetThread:output_type -> alis.agui.history.v1.Thread
	16, // 28: alis.agui.history.v1.ThreadService.DeleteThread:output_type -> google.protobuf.Empty
	1,  // 29: alis.agui.history.v1.ThreadService.GetUserThreadState:output_type -> alis.agui.history.v1.UserThreadState
	1,  // 30: alis.agui.history.v1.ThreadService.UpdateUserThreadState:output_type -> alis.agui.history.v1.UserThreadState
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_alis_agui_history_v1_history_proto_init() }
func file_alis_agui_history_v1_history_proto_init() {
	if File_alis_agui_history_v1_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_agui_history_v1_history_proto_rawDesc), len(file_alis_agui_history_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alis_agui_history_v1_history_proto_goTypes,
		DependencyIndexes: file_alis_agui_history_v1_history_proto_depIdxs,
		MessageInfos:      file_alis_agui_history_v1_history_proto_msgTypes,
	}.Build()
	File_alis_agui_history_v1_history_proto = out.File
	file_alis_agui_history_v1_history_proto_goTypes = nil
	file_alis_agui_history_v1_history_proto_depIdxs = nil
}
