// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/iam/v1/group.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-02 09:31:21 UTC

package iam

const (
	// GroupsService_GetIamPolicy_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.GetIamPolicy method.
	GroupsService_GetIamPolicy_FullMethodDescription = ""
	// GroupsService_SetIamPolicy_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.SetIamPolicy method.
	GroupsService_SetIamPolicy_FullMethodDescription = ""
	// GroupsService_TestIamPermissions_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.TestIamPermissions method.
	GroupsService_TestIamPermissions_FullMethodDescription = ""
	// GroupsService_AddIamBindings_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.AddIamBindings method.
	GroupsService_AddIamBindings_FullMethodDescription = ""
	// GroupsService_RemoveIamBindings_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.RemoveIamBindings method.
	GroupsService_RemoveIamBindings_FullMethodDescription = ""
	// GroupsService_GetGroup_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.GetGroup method.
	GroupsService_GetGroup_FullMethodDescription = ""
	// GroupsService_CreateGroup_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.CreateGroup method.
	GroupsService_CreateGroup_FullMethodDescription = ""
	// GroupsService_UpdateGroup_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.UpdateGroup method.
	GroupsService_UpdateGroup_FullMethodDescription = ""
	// GroupsService_DeleteGroup_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.DeleteGroup method.
	GroupsService_DeleteGroup_FullMethodDescription = ""
	// GroupsService_ListGroups_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.ListGroups method.
	GroupsService_ListGroups_FullMethodDescription = ""
	// GroupsService_SyncGroup_FullMethodDescription returns the description of the alis.open.iam.v1.GroupsService.SyncGroup method.
	GroupsService_SyncGroup_FullMethodDescription = ""
)
