// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/iam/v1/user.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-02 09:31:21 UTC

package iam

const (
	// UsersService_ValidateMessage_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.ValidateMessage method.
	UsersService_ValidateMessage_FullMethodDescription = ""
	// UsersService_RetrieveRules_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.RetrieveRules method.
	UsersService_RetrieveRules_FullMethodDescription = ""
	// UsersService_GetIamPolicy_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.GetIamPolicy method.
	UsersService_GetIamPolicy_FullMethodDescription = ""
	// UsersService_SetIamPolicy_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.SetIamPolicy method.
	UsersService_SetIamPolicy_FullMethodDescription = ""
	// UsersService_TestIamPermissions_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.TestIamPermissions method.
	UsersService_TestIamPermissions_FullMethodDescription = ""
	// UsersService_AddIamBindings_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.AddIamBindings method.
	UsersService_AddIamBindings_FullMethodDescription = ""
	// UsersService_RemoveIamBindings_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.RemoveIamBindings method.
	UsersService_RemoveIamBindings_FullMethodDescription = ""
	// UsersService_GetUser_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.GetUser method.
	UsersService_GetUser_FullMethodDescription = ""
	// UsersService_CreateUser_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.CreateUser method.
	UsersService_CreateUser_FullMethodDescription = ""
	// UsersService_UpdateUser_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.UpdateUser method.
	UsersService_UpdateUser_FullMethodDescription = ""
	// UsersService_DeleteUser_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.DeleteUser method.
	UsersService_DeleteUser_FullMethodDescription = ""
	// UsersService_ListUsers_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.ListUsers method.
	UsersService_ListUsers_FullMethodDescription = ""
	// UsersService_RetrieveUserByEmail_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.RetrieveUserByEmail method.
	UsersService_RetrieveUserByEmail_FullMethodDescription = ""
	// UsersService_LookupUser_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.LookupUser method.
	UsersService_LookupUser_FullMethodDescription = ""
	// UsersService_BatchRetrieveMaskedUsers_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.BatchRetrieveMaskedUsers method.
	UsersService_BatchRetrieveMaskedUsers_FullMethodDescription = ""
	// UsersService_RetrieveMaskedUsers_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.RetrieveMaskedUsers method.
	UsersService_RetrieveMaskedUsers_FullMethodDescription = ""
	// UsersService_RetrieveMaskedUser_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.RetrieveMaskedUser method.
	UsersService_RetrieveMaskedUser_FullMethodDescription = ""
	// UsersService_EditUserInfo_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.EditUserInfo method.
	UsersService_EditUserInfo_FullMethodDescription = ""
	// UsersService_EditUserMetadata_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.EditUserMetadata method.
	UsersService_EditUserMetadata_FullMethodDescription = ""
	// UsersService_RetrieveMyUser_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.RetrieveMyUser method.
	UsersService_RetrieveMyUser_FullMethodDescription = ""
	// UsersService_EditMyInfo_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.EditMyInfo method.
	UsersService_EditMyInfo_FullMethodDescription = ""
	// UsersService_EditMyMetadata_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.EditMyMetadata method.
	UsersService_EditMyMetadata_FullMethodDescription = ""
	// UsersService_RemoveMyUser_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.RemoveMyUser method.
	UsersService_RemoveMyUser_FullMethodDescription = ""
	// UsersService_SyncToGoogleGroup_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.SyncToGoogleGroup method.
	UsersService_SyncToGoogleGroup_FullMethodDescription = ""
	// UsersService_SetUserPicture_FullMethodDescription returns the description of the alis.open.iam.v1.UsersService.SetUserPicture method.
	UsersService_SetUserPicture_FullMethodDescription = ""
)
