// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/adk/sessions/v1/sessions.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-06-24 12:01:22 UTC

package v1

const (
	// SessionService_CreateSession_FullMethodDescription returns the description of the alis.adk.sessions.v1.SessionService.CreateSession method.
	SessionService_CreateSession_FullMethodDescription = ""
	// SessionService_GetSession_FullMethodDescription returns the description of the alis.adk.sessions.v1.SessionService.GetSession method.
	SessionService_GetSession_FullMethodDescription = ""
	// SessionService_ListSessions_FullMethodDescription returns the description of the alis.adk.sessions.v1.SessionService.ListSessions method.
	SessionService_ListSessions_FullMethodDescription = ""
	// SessionService_UpdateSession_FullMethodDescription returns the description of the alis.adk.sessions.v1.SessionService.UpdateSession method.
	SessionService_UpdateSession_FullMethodDescription = ""
	// SessionService_DeleteSession_FullMethodDescription returns the description of the alis.adk.sessions.v1.SessionService.DeleteSession method.
	SessionService_DeleteSession_FullMethodDescription = ""
	// SessionService_GetEvent_FullMethodDescription returns the description of the alis.adk.sessions.v1.SessionService.GetEvent method.
	SessionService_GetEvent_FullMethodDescription = ""
	// SessionService_ListEvents_FullMethodDescription returns the description of the alis.adk.sessions.v1.SessionService.ListEvents method.
	SessionService_ListEvents_FullMethodDescription = ""
	// SessionService_AppendEvent_FullMethodDescription returns the description of the alis.adk.sessions.v1.SessionService.AppendEvent method.
	SessionService_AppendEvent_FullMethodDescription = ""
)
