// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/px/v1/px.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-02 09:34:09 UTC

package px

const ()
