// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/options/v1/options.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-06-24 12:05:45 UTC

package v1

const ()
